server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB+NAME:product-db}?createDatabaseIfNotExist=true&timeZone=UTC
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop     # data definition languenge -- or lingyagem de difinição de dados
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect